# Replaces the hand-drawn outline in js\data\coastline.js with Natural Earth's
# surveyed 110m coastline (public domain).
#
#   powershell -ExecutionPolicy Bypass -File tools\fetch-map.ps1
#
# The globe reads whatever is in that file, so this changes nothing else.
# Re-run tools\validate.js afterwards, and commit the result.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$out  = Join-Path $root "js\data\coastline.js"
$url  = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_coastline.geojson"

Write-Host "Fetching Natural Earth 110m coastline ..."
$geo = Invoke-RestMethod -Uri $url -UseBasicParsing

$rings = @()
foreach ($f in $geo.features) {
  $g = $f.geometry
  if ($g.type -eq "LineString")      { $rings += ,$g.coordinates }
  elseif ($g.type -eq "MultiLineString") { foreach ($part in $g.coordinates) { $rings += ,$part } }
}
Write-Host "$($rings.Count) coastline rings."

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* =====================================================================")
[void]$sb.AppendLine("   COASTLINE — Natural Earth 110m, public domain.")
[void]$sb.AppendLine("   Generated by tools/fetch-map.ps1. Do not edit by hand; re-run it.")
[void]$sb.AppendLine("   Coasts only. No borders — see the note in js/globe.js.")
[void]$sb.AppendLine("   ===================================================================== */")
[void]$sb.AppendLine("")
[void]$sb.AppendLine('const COASTLINE_SOURCE = "natural-earth-110m";')
[void]$sb.AppendLine("")
[void]$sb.AppendLine("const COASTLINE = {")
[void]$sb.AppendLine("  land: [")
foreach ($r in $rings) {
  if ($r.Count -lt 3) { continue }
  $pts = foreach ($c in $r) { "[{0},{1}]" -f [math]::Round($c[0],2), [math]::Round($c[1],2) }
  [void]$sb.AppendLine("    [" + ($pts -join ",") + "],")
}
[void]$sb.AppendLine("  ],")
[void]$sb.AppendLine("  seas: [],")
[void]$sb.AppendLine("};")

[System.IO.File]::WriteAllText($out, $sb.ToString())
Write-Host "Wrote $out"
Write-Host "Now run:  node tools\validate.js"
