#!/usr/bin/env bash
# Replaces the hand-drawn outline in js/data/coastline.js with Natural Earth's
# surveyed 110m coastline (public domain). Needs curl and python3.
set -euo pipefail
cd "$(dirname "$0")/.."
url=https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_coastline.geojson
echo "Fetching Natural Earth 110m coastline ..."
curl -fsSL "$url" -o /tmp/ne_coast.geojson
python3 - <<'PY'
import json
geo = json.load(open('/tmp/ne_coast.geojson'))
rings = []
for f in geo['features']:
    g = f['geometry']
    if g['type'] == 'LineString': rings.append(g['coordinates'])
    elif g['type'] == 'MultiLineString': rings.extend(g['coordinates'])
rings = [r for r in rings if len(r) >= 3]
with open('js/data/coastline.js', 'w', newline='\n') as fh:
    fh.write('/* =====================================================================\n')
    fh.write('   COASTLINE — Natural Earth 110m, public domain.\n')
    fh.write('   Generated by tools/fetch-map.sh. Do not edit by hand; re-run it.\n')
    fh.write('   Coasts only. No borders — see the note in js/globe.js.\n')
    fh.write('   ===================================================================== */\n\n')
    fh.write('const COASTLINE_SOURCE = "natural-earth-110m";\n\n')
    fh.write('const COASTLINE = {\n  land: [\n')
    for r in rings:
        fh.write('    [' + ','.join('[%g,%g]' % (round(c[0],2), round(c[1],2)) for c in r) + '],\n')
    fh.write('  ],\n  seas: [],\n};\n')
print('%d rings written to js/data/coastline.js' % len(rings))
PY
echo "Now run:  node tools/validate.js"
